# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2023
# This file is distributed under the same license as the pandas package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pandas 2.1.3\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-11-12 17:37+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../source/reference/api/pandas.errors.MergeError.rst:2
msgid "pandas.errors.MergeError"
msgstr ""

#: ../../../../.local/lib/python3.10/site-packages/pandas/errors/__init__.py:docstring of pandas.errors.MergeError:2
msgid "Exception raised when merging data."
msgstr ""

#: ../../../../.local/lib/python3.10/site-packages/pandas/errors/__init__.py:docstring of pandas.errors.MergeError:4
msgid "Subclass of ``ValueError``."
msgstr ""

#: ../../../../.local/lib/python3.10/site-packages/pandas/errors/__init__.py:docstring of pandas.errors.MergeError:18
msgid "Examples"
msgstr ""
